name = "skyzen-worker"
main = "worker.mjs"
compatibility_date = "2024-10-01"
workers_dev = true

[[rules]]
type = "ESModule"
globs = ["**/*.mjs", "**/*.js"]
fallthrough = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
